### ISSUE TITLE
W2RC serialization fails due to semantic version of release

### ISSUE THREAD

**Issue by soulson** [rfuzzo/WolvenManager#2]
Using the CR2W command to serialize files to json with release `1.4` fails.

This seems to be because part of the json output writer attempts to read the assembly version of `WolvenManager.UI.dll` and parse it as a semantic version. The semver library is very strict and requires a patch version, without which it throws an exception. Changing the assembly info version attribute on `WolvenManager.UI.dll` to `1.4.0` using dnspy fixes the issue, which leads me to believe that the only thing needed is to change the project version attribute to `1.4.0`, but I don't have a build environment configured to test this at the moment.

```cs
[assembly: AssemblyInformationalVersion("1.4.0")]
```

**Comment by rfuzzo** [comment]
Thank you! I changed the version in https://github.com/rfuzzo/WolvenManager/releases/tag/1.4.1
